name: square_timer
description: a social recipe app to keep track of new dishes, and share with friends.

publish_to: "none"
version: 1.0.0+1

environment:
  sdk: ">=2.17.5 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  google_fonts: ^5.0.0
  provider: ^6.0.3
  flutter_colorpicker: ^1.0.3
  intl: ^0.17.0
  uuid: ^3.0.6
  file: ^6.1.4
  firebase_core: ^2.14.0
  firebase_auth: ^4.6.3
  google_sign_in: ^5.2.3
  flutter_signin_button: ^2.0.0
  shared_preferences: ^2.1.2
  visibility_detector: ^0.4.0+2
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.1

flutter:
  uses-material-design: true
  assets:
    - assets/
    - assets/data/emoji_list.json